/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthLayout: typeof import('./src/layouts/AuthLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IFeatherLock: typeof import('~icons/feather/lock')['default']
    IFeatherUser: typeof import('~icons/feather/user')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
